// Generated by gencpp from file deu_ros/TwoInts.msg
// DO NOT EDIT!


#ifndef DEU_ROS_MESSAGE_TWOINTS_H
#define DEU_ROS_MESSAGE_TWOINTS_H

#include <ros/service_traits.h>


#include <deu_ros/TwoIntsRequest.h>
#include <deu_ros/TwoIntsResponse.h>


namespace deu_ros
{

struct TwoInts
{

typedef TwoIntsRequest Request;
typedef TwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TwoInts
} // namespace deu_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deu_ros::TwoInts > {
  static const char* value()
  {
    return "732182ffae20073c520fb831c7ee33cd";
  }

  static const char* value(const ::deu_ros::TwoInts&) { return value(); }
};

template<>
struct DataType< ::deu_ros::TwoInts > {
  static const char* value()
  {
    return "deu_ros/TwoInts";
  }

  static const char* value(const ::deu_ros::TwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::deu_ros::TwoIntsRequest> should match
// service_traits::MD5Sum< ::deu_ros::TwoInts >
template<>
struct MD5Sum< ::deu_ros::TwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deu_ros::TwoInts >::value();
  }
  static const char* value(const ::deu_ros::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deu_ros::TwoIntsRequest> should match
// service_traits::DataType< ::deu_ros::TwoInts >
template<>
struct DataType< ::deu_ros::TwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::deu_ros::TwoInts >::value();
  }
  static const char* value(const ::deu_ros::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deu_ros::TwoIntsResponse> should match
// service_traits::MD5Sum< ::deu_ros::TwoInts >
template<>
struct MD5Sum< ::deu_ros::TwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deu_ros::TwoInts >::value();
  }
  static const char* value(const ::deu_ros::TwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deu_ros::TwoIntsResponse> should match
// service_traits::DataType< ::deu_ros::TwoInts >
template<>
struct DataType< ::deu_ros::TwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::deu_ros::TwoInts >::value();
  }
  static const char* value(const ::deu_ros::TwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEU_ROS_MESSAGE_TWOINTS_H
